### ISSUE TITLE
does not work with jekyll 4.0.0

### ISSUE THREAD

**Issue by allenbrunson** [MartinThoma/jekyll-gallery-tag#1]
i was using this to generate image galleries on my site a couple of years ago. i went to generate a new version of my site, and i discovered that this plugin has stopped working. i get:

gallery_tag.rb:67:in `render': undefined method `each' for nil:NilClass (NoMethodError)

any chance this can be updated for the current version of jekyll?

**Comment by MartinThoma** [comment]
@allenbrunson I don't use jekyll anymore because it was too slow. I switched to Python / pelican. I will not write an update, but feel free to create a PR.
